### ISSUE TITLE
Quarkus with quarkus-cxf native build fails

### ISSUE THREAD

**Issue by chet20r** [chet20r/quarkus-cxf-interceptor-issue#1]
Running a native build for a simple service that uses a quarkus-cxf client fails with the following error 

`$ mvn clean package -Dnative -pl sample-rest -am -Dquarkus.native.container-build=true` // from the parent maven project

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int):
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.lambda$defineClass$0(ClassGeneratorClassLoader.java:148)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader$$Lambda$923/0x00000007c1da6840.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
```

My environment settings
1. OS - Mac OS Catalina 10.15.7
2. Java 
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
3. maven version 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/craju6/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Users/craju6/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```
[native.log](https://github.com/chet20r/quarkus-cxf-interceptor-issue/files/6026502/native.log)

**Comment by shumonsharif** [comment]
Hey @chet20r try with the latest commit I just pushed to your codebase.

It appears additionalBuildArgs was deprecated `[https://github.com/quarkusio/quarkus/issues/12666#issuecomment-707596054]` in favor of a property called `quarkus.native.additional-build-args`, so looking at your log outputs, you can see that the `--report-unsupported-elements-at-runtime` flag never gets passed to the native image builder.

We must have had some slight difference in our environment / project setup ... because the additionalBuildArgs worked fine for me.

**Comment by dufoli** [comment]
ohh yeah I have fixed it in quarkiverse cxf too. Last version of quarkus has removed this option support. There is a new process.
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13

**Comment by dufoli** [comment]
it is fiexd on cxf with 2 commit:
https://github.com/quarkiverse/quarkus-cxf/commit/c89e4655cdfc483589d333381c21620cd00e5be5
https://github.com/quarkiverse/quarkus-cxf/commit/f64a893ca01d70539e7ec25fe962682e65192799

You have to add in POM
```
<properties>
                <quarkus.package.type>native</quarkus.package.type>
                <quarkus.native.report-errors-at-runtime>true</quarkus.native.report-errors-at-runtime>
</properties>
```

and remove plugin with quarkus-maven-plugin

**Comment by shumonsharif** [comment]
Hey @chet20r any luck with your native testing?  I'm ultimately curious how AWS Lambda works out for you ... please keep us posted on both your successes and if you run into any issues ...

Also, is this the approach you are using?  
https://quarkus.io/guides/amazon-lambda#deploy-to-aws-lambda-custom-native-runtime

**Comment by chet20r** [comment]
Hi @shumonsharif. I tried building native and it did build a native executable without any errors this time. However, there are two problems I am facing.

1. The native executable in the `sample-rest/target/` folder is close to 100 MB 😱 compared to the lambda function size in JVM mode which is around 30MB. I did get some warnings while building for native which is below

```
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] objcopy executable not found in PATH. Debug symbols will not be separated from executable.
```
2. When I run the native executable, i get `sample-rest-1.0.0-SNAPSHOT-runner: sample-rest-1.0.0-SNAPSHOT-runner: cannot execute binary file`. It looks like something is wrong with the binary format that was built (I am on a Mac x86 architecture) but not sure yet.

And yes, we are planning to use the approach in the link you shared by building an aws custom lambda runtime to run the executable.

**Comment by shumonsharif** [comment]
Hey @chet20r I believe debug symbols are why you're seeing the large file size; it appears they are getting bundled into your executable.  Take a look here, it explains why those are getting bundled, and how to control it.

https://quarkus.io/guides/building-native-image#debugging-native-executable

Also, is there a reason you are running the containerized native build?  That is likely the reason your native executable doesn't run on Mac OS.  You should run with `-Dquarkus.native.container-build=false` if you'd like it to execute on Mac OS.

**Comment by chet20r** [comment]
Thanks @shumonsharif  I haven't had a chance to build natively on Mac OS. Even if I do, the problem is our CI/CD would  require us to build using docker containers and I would probably hit the same problem there. Anyways, I've put this on the back burner for a bit now and will revisit it soon. Until then I'll keep this issue open 😄

**Comment by wanderingfella** [comment]
I have hit the exact same issue.
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int): 
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.lambda$defineClass$0(ClassGeneratorClassLoader.java:148)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader$$Lambda$1018/0x00000007c1fe8040.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:211)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:164)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:293)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

```

This is using a remote docker daemon to build the native image.
It's being built like this

./gradlew build -Dquarkus.package.type=native -Dquarkus.native.remote-container-build=true

From Jenkins, using a remote docker container.

I am using quarkus 1.13.7.Final and quarkus-cxf:0.8. I am hoping to run it in AWS Lambda.

**Comment by dufoli** [comment]
Which version of graalvm? @wanderingfella

**Comment by wanderingfella** [comment]
@dufoli Thanks.
It looks to be using
`Running Quarkus native-image plugin on GraalVM Version 21.0.0.2`

I have added 
`-Dquarkus.native.report-errors-at-runtime=true`
to the build command which looks to have resolved it, concerned it might come back at runtime though.

Having issues with the build process running out of memory at the moment, looking into that, but that should be fairly straightforward.

**Comment by dufoli** [comment]
hmm can you try with 0.9 version of quarkus cxf because we fix something related to defineClass here : 
https://github.com/quarkiverse/quarkus-cxf/pull/257
and use last version of CXF too.
Because ClassGeneratorClassLoader is the new system witch do not use class generation in native mode.
But XECParameters seems to call it which seems very strange to me because it is out of cxf.

**Comment by wanderingfella** [comment]
Just tried with 
io.quarkiverse.cxf:quarkus-cxf:0.9

It looks like it's bringing in

+--- io.quarkiverse.cxf:quarkus-cxf:0.9
|    +--- io.quarkus:quarkus-arc:2.0.0.Final -> 1.13.7.Final (*)
|    +--- org.apache.cxf:cxf-rt-frontend-jaxws:3.4.4
|    |    +--- xml-resolver:xml-resolver:1.2
|    |    +--- org.apache.cxf:cxf-core:3.4.4
|    |    |    +--- org.glassfish.jaxb:jaxb-runtime:2.3.4 -> 2.3.3-b02

version 3.4.4 of cxf.

Which looks to be the latest version.

https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-frontend-jaxws
`Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int): 
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.lambda$defineClass$0(ClassGeneratorClassLoader.java:148)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader$$Lambda$1039/0x00000007c1fd6c40.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:211)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:164)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:293)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)`

**Comment by wanderingfella** [comment]
Just as an update.
With -Dquarkus.native.report-errors-at-runtime=true it builds fine natively.
And it also runs fine in a Lambda.

I was seeing an issue in a JVM where the first call to CXF took 7 or 8 seconds. 

In native, it's a tiny amount of time.
The whole performance is phenomenal.

I still have work to do, but it seems excellent.
